sudo: false
language: generic
cache:
  directories:
  - "$HOME/.stack"
matrix:
  include:
  - compiler: "#Linux"
    addons:
      apt:
        packages:
        - libgmp-dev
  - compiler: "#macOS"
    os: osx
before_install:
- unset CC
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack build --ghc-options -O2 --pedantic

notifications:
  slack: dyti234:6KAy6KgKN7R8TJbsIxsgukNF