name:                PkMnRipper
version:             0.1.0.0
github:              "tavandev/PkMnRipper"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/githubuser/PokeRipper#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers

library:
  source-dirs: src

executables:
  PkMnRipper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PkMnRipper

tests:
  PkMnRipper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PkMnRipper
